# Generated by Django 4.0.2 on 2022-03-06 15:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('markets', '0001_initial'),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='product_category', to='products.productcategory'),
        ),
        migrations.AlterField(
            model_name='product',
            name='market',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='product_market', to='markets.market'),
        ),
    ]
