# Generated by Django 4.0.2 on 2022-03-20 06:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0002_alter_product_category_alter_product_market'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductLikeUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reg_date', models.DateTimeField(auto_now_add=True, verbose_name='좋아요 등록 시간')),
                ('update_date', models.DateTimeField(auto_now=True, verbose_name='수정 시간')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='product_liked_user',
            field=models.ManyToManyField(related_name='liked_product', through='products.ProductLikeUser', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='productlikeuser',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product'),
        ),
        migrations.AddField(
            model_name='productlikeuser',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
